-- Create demo users in Supabase
-- Run this in your Supabase SQL Editor

-- Insert demo users into the users table
INSERT INTO users (
  id,
  email,
  name,
  role,
  capabilities,
  company,
  location,
  phone,
  avatar,
  is_verified,
  subscription_status,
  fica_status,
  rating,
  total_deals,
  total_transactions,
  reputation_score,
  business_type,
  created_at,
  updated_at
) VALUES 
(
  'demo-farmer-1',
  'farmer@demo.com',
  'Demo Farmer',
  'buyer',
  ARRAY['buy', 'sell', 'transport'],
  'Demo Mixed Farm',
  'Free State',
  '+27 82 123 4567',
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face',
  true,
  'active',
  'verified',
  4.8,
  45,
  67,
  92,
  'company',
  NOW(),
  NOW()
),
(
  'demo-seller-1',
  'seller@demo.com',
  'Sarah Johnson',
  'seller',
  ARRAY['sell', 'buy', 'transport'],
  'Demo Maize Farm',
  'Free State',
  '+27 82 234 5678',
  'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=150&h=150&fit=crop&crop=face',
  true,
  'active',
  'verified',
  4.9,
  23,
  34,
  95,
  'cooperative',
  NOW(),
  NOW()
),
(
  'demo-transporter-1',
  'transporter@demo.com',
  'Mike Transport',
  'transporter',
  ARRAY['transport', 'sell', 'buy'],
  'Demo Transport Services',
  'Cape Town, Western Cape',
  '+27 82 345 6789',
  'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop&crop=face',
  true,
  'active',
  'verified',
  4.7,
  67,
  89,
  88,
  'company',
  NOW(),
  NOW()
)
ON CONFLICT (email) DO NOTHING;
